#!/bin/bash
#atualize os repositórios e pacotes do termux
pkg update
pkg upgrade
#instalar pacotes
pkg install -y python coreutils nano clang mosquitto nodejs openssh termux-api libjpeg-turbo nano

#Comando para não deixar o termux ser fechado e continuar a execução em segundo plano.
termux-wake-lock

#Executar o Mosquitto para testar:
#mosquitto

#instalar HA em um Virtual Enviroment
python3 -m venv homeassistant
cd homeassistant
source bin/activate
python3 -m pip install wheel
python3 -m pip install Pillow
python3 -m pip install homeassistant

#executar o Home Assistant
#hass
